name: CI/CD

on:
  push:
    branches: 
      - main 
      - develop 
      - 'feature/*'
  workflow_dispatch:

jobs:
  backend-ci:
    name: Backend CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.14.0'

      - name: Install dependencies
        run: npm install
        working-directory: campersBack/

      - name: Run tests
        run: npm run test
        working-directory: campersBack/

      - name: Build
        run: npm run build
        working-directory: campersBack/

  frontend-deploy:
    name: Frontend CI & Deploy to Vercel
    runs-on: ubuntu-latest
    needs: backend-ci 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install
        working-directory: campersFront/

      - name: Build frontend
        run: npm run build
        working-directory: campersFront/

      - name: Deploy to Vercel
        run: |
          npm install -g vercel
          vercel --prod --token=${{ secrets.VERCEL_TOKEN }} --confirm
        working-directory: ./vercelApp/campersFront
